tasks:
  - init: |
      pip install --upgrade pip
      pip install --user qmk
      qmk setup --yes
      ln -s /workspace/qmk-massdrop-ctrl /home/gitpod/qmk_firmware/keyboards/massdrop/ctrl/keymaps/nils
    command: qmk compile -kb massdrop/ctrl -km nils